version: "3.9"

services:

  db_server:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: bootcampdb
      MYSQL_ROOT_PASSWORD: fooda
    ports:
      - 3333:3306

  db_admin:
    image: adminer:4.8.1-standalone
    restart: always
    depends_on:
      - db_server
    ports:
      - 9999:8080

  backend:
    image: yilmazchef/bootcamp-spring-boot-api:latest
    depends_on:
      - db_server
      - db_admin
    links:
      - db_server:db_server
    ports:
      - 8888:8080